import type { Case, AgentAction, Communication, DashboardStats, CaseFile } from "./types"

export const mockCases: Case[] = [
  {
    id: "case-001",
    clientName: "Sarah Johnson",
    caseType: "Personal Injury",
    status: "active",
    priority: "high",
    assignedTo: "Emily Rodriguez",
    createdAt: "2025-01-15",
    lastActivity: "2025-01-23",
    description: "Slip and fall incident at retail location. Client sustained back injuries.",
    nextAction: "Schedule medical evaluation",
  },
  {
    id: "case-002",
    clientName: "Michael Chen",
    caseType: "Contract Dispute",
    status: "active",
    priority: "medium",
    assignedTo: "Emily Rodriguez",
    createdAt: "2025-01-10",
    lastActivity: "2025-01-22",
    description: "Breach of contract regarding software development agreement.",
    nextAction: "Review contract terms",
  },
  {
    id: "case-003",
    clientName: "Jennifer Martinez",
    caseType: "Employment Law",
    status: "pending",
    priority: "urgent",
    assignedTo: "Emily Rodriguez",
    createdAt: "2025-01-20",
    lastActivity: "2025-01-24",
    description: "Wrongful termination claim. Client was dismissed without proper notice.",
    nextAction: "Gather employment records",
  },
  {
    id: "case-004",
    clientName: "David Thompson",
    caseType: "Real Estate",
    status: "on-hold",
    priority: "low",
    assignedTo: "Emily Rodriguez",
    createdAt: "2024-12-05",
    lastActivity: "2025-01-10",
    description: "Property boundary dispute with neighbor.",
    nextAction: "Awaiting survey results",
  },
  {
    id: "case-005",
    clientName: "Lisa Anderson",
    caseType: "Family Law",
    status: "active",
    priority: "high",
    assignedTo: "Emily Rodriguez",
    createdAt: "2025-01-18",
    lastActivity: "2025-01-25",
    description: "Child custody modification request.",
    nextAction: "Prepare court documents",
  },
  {
    id: "case-006",
    clientName: "Robert Williams",
    caseType: "Criminal Defense",
    status: "closed",
    priority: "medium",
    assignedTo: "Emily Rodriguez",
    createdAt: "2024-11-20",
    lastActivity: "2025-01-15",
    description: "DUI case - successfully negotiated reduced charges.",
    nextAction: "Case closed",
  },
]

export const mockAgentActions: AgentAction[] = [
  {
    id: "action-001",
    caseId: "case-001",
    caseName: "Sarah Johnson - Personal Injury",
    actionType: "Send Document Request",
    description: "Request medical records from St. Mary's Hospital for injury documentation",
    suggestedBy: "AI Assistant",
    status: "pending",
    createdAt: "2025-01-25T10:30:00",
    reasoning:
      "Medical records are essential for establishing the extent of injuries and supporting the claim. The 30-day statute window is approaching.",
    impact: "high",
  },
  {
    id: "action-002",
    caseId: "case-003",
    caseName: "Jennifer Martinez - Employment Law",
    actionType: "Schedule Client Meeting",
    description: "Schedule follow-up meeting to review employment contract and termination letter",
    suggestedBy: "AI Assistant",
    status: "pending",
    createdAt: "2025-01-25T09:15:00",
    reasoning:
      "Client has not responded to initial document request. A meeting will help clarify details and maintain case momentum.",
    impact: "medium",
  },
  {
    id: "action-003",
    caseId: "case-002",
    caseName: "Michael Chen - Contract Dispute",
    actionType: "Draft Legal Brief",
    description: "Prepare preliminary brief outlining breach of contract claims",
    suggestedBy: "AI Assistant",
    status: "pending",
    createdAt: "2025-01-25T14:20:00",
    reasoning:
      "Contract analysis is complete. Next step is to formalize our position before mediation scheduled for next month.",
    impact: "high",
  },
  {
    id: "action-004",
    caseId: "case-005",
    caseName: "Lisa Anderson - Family Law",
    actionType: "File Court Motion",
    description: "File motion for temporary custody modification",
    suggestedBy: "AI Assistant",
    status: "approved",
    createdAt: "2025-01-24T11:00:00",
    reasoning:
      "All required documentation has been gathered. Filing now ensures hearing can be scheduled within required timeframe.",
    impact: "high",
  },
  {
    id: "action-005",
    caseId: "case-001",
    caseName: "Sarah Johnson - Personal Injury",
    actionType: "Contact Witness",
    description: "Reach out to store manager who witnessed the incident",
    suggestedBy: "AI Assistant",
    status: "rejected",
    createdAt: "2025-01-23T16:45:00",
    reasoning:
      "Witness testimony would strengthen the case. Manager's statement could corroborate client's account of unsafe conditions.",
    impact: "medium",
  },
]

export const mockCommunications: Communication[] = [
  {
    id: "comm-001",
    caseId: "case-001",
    type: "email",
    subject: "Medical Records Request",
    from: "emily.rodriguez@lawfirm.com",
    to: "records@stmarys.hospital.com",
    date: "2025-01-23T14:30:00",
    content:
      "Dear Records Department,\n\nI am writing to request medical records for our client, Sarah Johnson (DOB: 05/12/1985), regarding treatment received on January 10, 2025...",
  },
  {
    id: "comm-002",
    caseId: "case-001",
    type: "call",
    subject: "Client Check-in Call",
    from: "Emily Rodriguez",
    to: "Sarah Johnson",
    date: "2025-01-22T10:00:00",
    content:
      "Discussed current recovery status and upcoming medical appointments. Client reports continued back pain. Advised to keep detailed log of symptoms.",
  },
  {
    id: "comm-003",
    caseId: "case-002",
    type: "email",
    subject: "Contract Review Findings",
    from: "emily.rodriguez@lawfirm.com",
    to: "michael.chen@email.com",
    date: "2025-01-22T16:20:00",
    content:
      "Dear Mr. Chen,\n\nI have completed my review of the software development contract. I have identified several key provisions that support your position...",
  },
  {
    id: "comm-004",
    caseId: "case-003",
    type: "document",
    subject: "Employment Records Received",
    from: "HR Department - TechCorp",
    to: "emily.rodriguez@lawfirm.com",
    date: "2025-01-24T09:15:00",
    content:
      "Received complete employment file including: hire date, performance reviews, termination letter, and final paycheck documentation.",
    attachments: ["employment_file.pdf", "termination_letter.pdf"],
  },
  {
    id: "comm-005",
    caseId: "case-005",
    type: "meeting",
    subject: "Client Consultation - Custody Case",
    from: "Emily Rodriguez",
    to: "Lisa Anderson",
    date: "2025-01-25T13:00:00",
    content:
      "Met with client to discuss custody modification strategy. Reviewed evidence of changed circumstances. Client provided updated school records and childcare documentation.",
  },
]

export const mockDashboardStats: DashboardStats = {
  totalCases: 6,
  activeCases: 3,
  pendingActions: 3,
  recentCommunications: 5,
}

export const mockCaseFiles: CaseFile[] = [
  // Case 001 - Sarah Johnson (Personal Injury) - 15 files
  {
    id: "file-001",
    caseId: "case-001",
    name: "BI CARRIER requesting info",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/BI+CARRIER+requesting+info_Redacted.pdf",
    type: "pdf",
    size: "2.3 MB",
    uploadedAt: "2025-01-16T10:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-002",
    caseId: "case-001",
    name: "EST-TOTALLOSS",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/EST-TOTALLOSS--14593-84-04-15-2019-16-18-02_Redacted.pdf",
    type: "pdf",
    size: "1.8 MB",
    uploadedAt: "2025-01-16T11:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-003",
    caseId: "case-001",
    name: "Property damage estimate",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/Property+damage+estimate_Redacted.pdf",
    type: "pdf",
    size: "1.2 MB",
    uploadedAt: "2025-01-17T09:15:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-004",
    caseId: "case-001",
    name: "EST-PHOTOS",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/EST-PHOTOS-04-15-2019_Redacted.pdf",
    type: "pdf",
    size: "5.4 MB",
    uploadedAt: "2025-01-17T14:20:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-005",
    caseId: "case-001",
    name: "Ltr from AutoOwners with offer of $18k",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/Ltr+from+AutoOwners+with+offer+of+%2418k_Redacted.pdf",
    type: "pdf",
    size: "890 KB",
    uploadedAt: "2025-01-18T10:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-006",
    caseId: "case-001",
    name: "PIP LOG as of 2_14_2020",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/PIP+LOG+as+of+2_14_2020_Redacted.pdf",
    type: "pdf",
    size: "1.5 MB",
    uploadedAt: "2025-01-19T11:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-007",
    caseId: "case-001",
    name: "POLICE REPORT",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/POLICE+REPORT+(1).pdf",
    type: "pdf",
    size: "3.2 MB",
    uploadedAt: "2025-01-19T15:45:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-008",
    caseId: "case-001",
    name: "File Notes",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+Notes.docx",
    type: "document",
    size: "45 KB",
    uploadedAt: "2025-01-20T09:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-009",
    caseId: "case-001",
    name: "Insurance Basics",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/Insurance+Basics.docx",
    type: "document",
    size: "67 KB",
    uploadedAt: "2025-01-20T10:15:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-010",
    caseId: "case-001",
    name: "LIEN - MEDICARE (2)",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/LIEN+-+MEDICARE+(2)_Redacted.pdf",
    type: "pdf",
    size: "780 KB",
    uploadedAt: "2025-01-21T13:20:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-011",
    caseId: "case-001",
    name: "LIEN - OPTUM FINAL LIEN",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/LIEN+-OPTUM+FINAL+LIEN+_Redacted.pdf",
    type: "pdf",
    size: "920 KB",
    uploadedAt: "2025-01-21T14:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-012",
    caseId: "case-001",
    name: "Call about demand",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+4-+call+about+demand.m4a",
    type: "audio",
    size: "3.5 MB",
    uploadedAt: "2025-01-22T10:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-013",
    caseId: "case-001",
    name: "Low offer - lawsuit discussion",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+4-+low+offer-+lawsuit.m4a",
    type: "audio",
    size: "4.2 MB",
    uploadedAt: "2025-01-22T11:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-014",
    caseId: "case-001",
    name: "First call",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+4+-+first+call.m4a",
    type: "audio",
    size: "2.8 MB",
    uploadedAt: "2025-01-22T14:15:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-015",
    caseId: "case-001",
    name: "2nd call",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+4-+2nd+call.m4a",
    type: "audio",
    size: "3.1 MB",
    uploadedAt: "2025-01-22T15:30:00",
    uploadedBy: "Emily Rodriguez",
  },

  // Case 002 - Michael Chen (Contract Dispute) - 12 files
  {
    id: "file-016",
    caseId: "case-002",
    name: "Police Report",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/Police+Report.pdf",
    type: "pdf",
    size: "2.7 MB",
    uploadedAt: "2025-01-11T09:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-017",
    caseId: "case-002",
    name: "INSURANCE - POLICY PROGRESSIVE",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/INSURANCE-+POLICY+PROGRESSIVE++.pdf",
    type: "pdf",
    size: "4.5 MB",
    uploadedAt: "2025-01-11T10:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-018",
    caseId: "case-002",
    name: "LIEN - MEDICARE (1)",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/LIEN+-+MEDICARE+(1)_Redacted.pdf",
    type: "pdf",
    size: "810 KB",
    uploadedAt: "2025-01-12T11:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-019",
    caseId: "case-002",
    name: "LIEN - OPTUM",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/LIEN+-+OPTUM+_Redacted.pdf",
    type: "pdf",
    size: "750 KB",
    uploadedAt: "2025-01-12T14:20:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-020",
    caseId: "case-002",
    name: "Progressive Dec",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/Progressive+Dec_Redacted.pdf",
    type: "pdf",
    size: "1.1 MB",
    uploadedAt: "2025-01-13T09:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-021",
    caseId: "case-002",
    name: "Geico Dec Page",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/Geico+Dec+Page_Redacted.PDF",
    type: "pdf",
    size: "890 KB",
    uploadedAt: "2025-01-13T10:45:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-022",
    caseId: "case-002",
    name: "Geico Policy",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/Geico+Policy_Redacted.pdf",
    type: "pdf",
    size: "3.8 MB",
    uploadedAt: "2025-01-14T11:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-023",
    caseId: "case-002",
    name: "LTR - OFFER 28k asking for sx records",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/LTR+-+OFFER+28k+asking+for+sx+recoreds.pdf",
    type: "pdf",
    size: "650 KB",
    uploadedAt: "2025-01-15T13:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-024",
    caseId: "case-002",
    name: "VM from Geico",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/VM+from+Geico+.wav",
    type: "audio",
    size: "1.2 MB",
    uploadedAt: "2025-01-16T09:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-025",
    caseId: "case-002",
    name: "LTR - CRN TO PROGRESSIVE",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/LTR+-+CRN+TO+PROGRESSIVE+.pdf",
    type: "pdf",
    size: "580 KB",
    uploadedAt: "2025-01-17T10:15:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-026",
    caseId: "case-002",
    name: "LTR - OFFER 24k again",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/LTR+-+OFFER-+24k+again.pdf",
    type: "pdf",
    size: "620 KB",
    uploadedAt: "2025-01-18T14:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-027",
    caseId: "case-002",
    name: "LTR - OFFER 28K",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/LTR+-+OFFER+28K++.pdf",
    type: "pdf",
    size: "640 KB",
    uploadedAt: "2025-01-19T11:30:00",
    uploadedBy: "Emily Rodriguez",
  },

  // Case 003 - Jennifer Martinez (Employment Law) - 18 files
  {
    id: "file-028",
    caseId: "case-003",
    name: "Offer 22k",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/ltr+-+offer+22%2C---.PDF",
    type: "pdf",
    size: "590 KB",
    uploadedAt: "2025-01-20T09:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-029",
    caseId: "case-003",
    name: "LTR - OFFER 24K",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/LTR+-+OFFER+24K.PDF",
    type: "pdf",
    size: "610 KB",
    uploadedAt: "2025-01-20T10:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-030",
    caseId: "case-003",
    name: "LTR - OFFER 25k",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/LTR+-+OFFER-25k.pdf",
    type: "pdf",
    size: "630 KB",
    uploadedAt: "2025-01-20T14:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-031",
    caseId: "case-003",
    name: "Initial Offer Letter",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/ltr+-+offer+.pdf",
    type: "pdf",
    size: "570 KB",
    uploadedAt: "2025-01-21T09:15:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-032",
    caseId: "case-003",
    name: "PD - EST-ESTIMATE",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/PD+-+EST-ESTIMATE--10394-07-08-03-2021-16-13-37_Redacted.pdf",
    type: "pdf",
    size: "1.9 MB",
    uploadedAt: "2025-01-21T11:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-033",
    caseId: "case-003",
    name: "PD - EST-PHOTOS1",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/PD+-+EST-PHOTOS1.pdf",
    type: "pdf",
    size: "4.2 MB",
    uploadedAt: "2025-01-21T13:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-034",
    caseId: "case-003",
    name: "PD - EST-PHOTOS",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/PD+-+EST-PHOTOS.pdf",
    type: "pdf",
    size: "3.8 MB",
    uploadedAt: "2025-01-21T14:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-035",
    caseId: "case-003",
    name: "Property Damage Photo 1",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/PD1.jpg",
    type: "image",
    size: "2.1 MB",
    uploadedAt: "2025-01-22T09:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-036",
    caseId: "case-003",
    name: "Property Damage Photo 2",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/PD%40.jpg",
    type: "image",
    size: "1.9 MB",
    uploadedAt: "2025-01-22T09:15:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-037",
    caseId: "case-003",
    name: "Scene Photo 1",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/Scene1.jpg",
    type: "image",
    size: "2.3 MB",
    uploadedAt: "2025-01-22T09:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-038",
    caseId: "case-003",
    name: "Scene Photo 2",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/Scene2.jpg",
    type: "image",
    size: "2.5 MB",
    uploadedAt: "2025-01-22T09:45:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-039",
    caseId: "case-003",
    name: "5 days after demand",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+3-+5+days+after+demand.m4a",
    type: "audio",
    size: "3.8 MB",
    uploadedAt: "2025-01-22T11:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-040",
    caseId: "case-003",
    name: "Call about Tender",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+3-+call+about+Tender.m4a",
    type: "audio",
    size: "2.9 MB",
    uploadedAt: "2025-01-22T13:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-041",
    caseId: "case-003",
    name: "Call about demand",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+3-+call+about+demand.m4a",
    type: "audio",
    size: "3.2 MB",
    uploadedAt: "2025-01-22T14:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-042",
    caseId: "case-003",
    name: "Call about offer",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+3-+call+about+offer.m4a",
    type: "audio",
    size: "2.7 MB",
    uploadedAt: "2025-01-23T09:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-043",
    caseId: "case-003",
    name: "Call about CRN",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+3-+call+about+CRN.m4a",
    type: "audio",
    size: "3.1 MB",
    uploadedAt: "2025-01-23T10:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-044",
    caseId: "case-003",
    name: "First call",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+3-+first+call.m4a",
    type: "audio",
    size: "2.5 MB",
    uploadedAt: "2025-01-23T13:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-045",
    caseId: "case-003",
    name: "2nd call",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+3+-+2nd+call.m4a",
    type: "audio",
    size: "2.8 MB",
    uploadedAt: "2025-01-23T14:30:00",
    uploadedBy: "Emily Rodriguez",
  },

  // Case 004 - David Thompson (Real Estate) - 8 files
  {
    id: "file-046",
    caseId: "case-004",
    name: "3rd call",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+3+-+3rd+call.m4a",
    type: "audio",
    size: "3.3 MB",
    uploadedAt: "2024-12-06T10:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-047",
    caseId: "case-004",
    name: "PIP LOG",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/PIP+LOG+_Redacted.pdf",
    type: "pdf",
    size: "1.4 MB",
    uploadedAt: "2024-12-07T11:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-048",
    caseId: "case-004",
    name: "4th call",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+3-+4th+call.m4a",
    type: "audio",
    size: "2.6 MB",
    uploadedAt: "2024-12-08T09:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-049",
    caseId: "case-004",
    name: "LTR - PIP EXHAUST",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/LTR+-+PIP+EXHAUST.PDF",
    type: "pdf",
    size: "720 KB",
    uploadedAt: "2024-12-10T14:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-050",
    caseId: "case-004",
    name: "CRASH REPORT",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/CRASH+REPORT.pdf",
    type: "pdf",
    size: "2.9 MB",
    uploadedAt: "2024-12-12T10:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-051",
    caseId: "case-004",
    name: "PIP payout",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/PIP+payout_Redacted.pdf",
    type: "pdf",
    size: "980 KB",
    uploadedAt: "2024-12-15T11:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-052",
    caseId: "case-004",
    name: "PL offer",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/PL+offer_Redacted.pdf",
    type: "pdf",
    size: "850 KB",
    uploadedAt: "2024-12-18T13:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-053",
    caseId: "case-004",
    name: "Property damage estimate and photos",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/Property+damage+estimate+and+photos.pdf",
    type: "pdf",
    size: "6.2 MB",
    uploadedAt: "2024-12-20T09:00:00",
    uploadedBy: "Emily Rodriguez",
  },

  // Case 005 - Lisa Anderson (Family Law) - 3 files
  {
    id: "file-054",
    caseId: "case-005",
    name: "3rd call",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/Fie+4-+3rd+call.m4a",
    type: "audio",
    size: "3.4 MB",
    uploadedAt: "2025-01-19T10:00:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-055",
    caseId: "case-005",
    name: "4th call",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/File+4-4th+call.m4a",
    type: "audio",
    size: "2.9 MB",
    uploadedAt: "2025-01-20T11:30:00",
    uploadedBy: "Emily Rodriguez",
  },
  {
    id: "file-056",
    caseId: "case-005",
    name: "SMS Records",
    url: "https://simplylaw.s3.us-east-1.amazonaws.com/sms_records_anonymized.csv",
    type: "csv",
    size: "125 KB",
    uploadedAt: "2025-01-22T14:00:00",
    uploadedBy: "Emily Rodriguez",
  },
]
