export const termOfServices = `
Terms of Service

Effective Date: March 1, 2025
Welcome to Simply Law (“we”, “us”, “our”). These Terms of Service (“Terms”) govern your access to and use of our website, platform and services (collectively, the “Services”). By using the Services, you agree to these Terms.

1. Acceptance of Terms
By accessing or using the Services, you warrant that you have read, understood and agree to be bound by these Terms and our Privacy Policy. If you do not agree, you must not use the Services.

2. Eligibility
You represent and warrant that you are at least 18 years old, or the minimum age required in your jurisdiction to access the Services, or that you have parental or guardian consent.
You further represent that you have authority to enter into these Terms on behalf of any organization for whom you use the Services.

3. Description of Services
Simply Law provides an AI-powered legal-assistance platform: you may submit case-related information, receive analysis, summaries, risk assessments, legal research pointers, document drafts, or other outputs generated by our AI and human oversight.
We do not provide attorney-client relationships or legal representation unless expressly agreed in a separate written engagement.

4. User Responsibilities
You agree to:
• Provide accurate, complete and up-to-date information when using the Services;
• Use the Services only for lawful purposes and in accordance with these Terms;
• Not submit confidential or privileged information unless you are authorized to do so;
• Not use the Services in a way that violates applicable laws (e.g., privacy laws, export controls, intellectual property laws);
• Comply with any instructions we may provide in connection with the Services.

5. Intellectual Property
All intellectual property rights in the Services, including the underlying AI models, software, documentation, content and trademarks, are owned by Simply Law or our licensors. Nothing in these Terms grants you any rights except as expressly set forth herein.

6. User Content
When you submit data, documents, or other materials (“User Content”) to the Services, you grant us a worldwide, non-exclusive, royalty-free licence to use, process, display, reproduce, modify and incorporate your User Content for the purpose of providing the Services, improving our platform (including training or refining AI models) and as otherwise described in our Privacy Policy.
You represent and warrant that you have all rights necessary to grant this licence and that the User Content does not infringe third-party rights or violate applicable law.

7. Disclaimers; No Legal Advice
The Services may provide legal-research, risk-analysis or document-assistance features, but they do not constitute legal advice, an attorney-client relationship or any substitute for consulting a qualified attorney.
We make no warranties that the Services will be error-free, complete or appropriate for your particular case.
You assume all risk associated with your reliance on the Services and agree you will seek independent legal advice when needed.

8. Limitation of Liability
To the maximum extent permitted by law, Simply Law and its affiliates, officers, directors, employees, agents or licensors will not be liable for any indirect, incidental, special, consequential or punitive damages, including loss of profits, loss of business, or loss of data, arising out of or related to your use of or inability to use the Services, even if advised of the possibility of such damages.
Our total aggregate liability to you for all claims arising in connection with these Terms shall not exceed the amounts paid by you to Simply Law for the Services in the 12 months preceding the event giving rise to the claim.

9. Termination
We may suspend or terminate your access to the Services at any time, with or without cause, including for violation of these Terms. On termination, you must stop using the Services. Sections that by their nature survive termination (e.g., Intellectual Property, Disclaimers, Limitation of Liability, Governing Law) will continue in full force.

10. Governing Law & Dispute Resolution
These Terms will be governed by and construed in accordance with the laws of the State of Florida, USA, without regard to conflict of law principles.
You and Simply Law agree to submit to the personal and exclusive jurisdiction of the courts located within Orange County, Florida, for any dispute arising out of or relating to these Terms or the Services.

11. Changes to Terms
We reserve the right to update or modify these Terms at any time by posting a revised version on our website. The “Effective Date” will be updated accordingly. Your continued use of the Services after that date means you accept the revised Terms.

12. Miscellaneous
Entire Agreement: These Terms plus the Privacy Policy constitute the entire agreement between you and Simply Law.
Severability: If any provision is held invalid or unenforceable, the remainder of the Terms will continue in effect.
Waiver: No waiver of any provision is effective unless in writing and signed by Simply Law.
`;
